Add BTC price fetching
foundryservices/bitcoin-subnet pull request #3
Opened 2024-08-02 20:33 UTC by sreefoundry

feat:
- add BTC price fetch method from yfinance
- add WBTC price fetch method from DEX Screener

2024-08-04 16:47 UTC, rahulfoundry submitted a review, later dismissed
LGTM

2024-08-04 17:47 UTC, rahulfoundry approved these changes

2024-08-05 16:30 UTC, mtrudeau-foundry-digital requested changes

2024-08-05 16:30 UTC, mtrudeau-foundry-digital commented on requirements.txt
> +aiohappyeyeballs==2.3.4
it looks like you only added yahoo finance as a dependency. please only add yahoo finance to the requirements text file

2024-08-05 16:30 UTC, mtrudeau-foundry-digital commented on template/utils/btc_price.py
> +    print(btc_hist)
do we need this print statement?

2024-08-05 16:30 UTC, mtrudeau-foundry-digital commented on template/utils/btc_price.py
> +        float: BTC price in USD.
are we returning a float or a dataframe?

2024-08-05 17:07 UTC, mtrudeau-foundry-digital approved these changes

2024-08-05 17:10 UTC, merged